# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Henri Woodcock
tagline:             'Under construction'
description:         'Data Science.'
url:                 http://henriwoodcock.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Henri Woodcock
  url:               https://github.com/henriwoodcock
  email:             henriwoodcock@gmail.com

# Custom vars
version:             1.0.0
